version: "3.8"
services:

  csv-ngsild-agent:
    build: ./csv_NGSILD_Agent
    hostname: csv-ngsild-agent
    container_name: csv-ngsild-agent
    networks:
      - circuloos
    ports:
      - "5000:5000"  # Prometheus server port
    environment:
      - CSV_AGENT_PORT=5000
      - NGSI_LD_CONTECT_BROKER_HOSTNAME=localhost
      - NGSI_LD_CONTECT_BROKER_PORT=1026 # if no port is given the CB is running behind a PEP proxy
      - ORION_LD_TENANT=circuloos_demo
      - CONTEXT_JSON=http://circuloos-ld-context/circuloos-context.jsonld

  leather_board_outline_full_image_demonstrating:
    build: ./leather_board_outline/full_image_demonstrating
    hostname: leather_board_outline_full_image_demonstrating
    container_name: leather_board_outline_full_image_demonstrating
    networks:
      - circuloos
    ports:
      - "8501:8501"  # Prometheus server port
