version: "3.8"

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "1m"
    max-file: "1"
    tag: "{{.Name}}"

services:
  # @context file is served from here
  ld-context:
    labels:
      org.eurodyn: 'circuloos'
      logging: "promtail"
      logging_jobname: "containerlogs"
    image: httpd:alpine
    hostname: circuloos-ld-context
    container_name: circuloos-ld-context
    expose:
        - "3004:80"
    networks:
      - circuloos
    volumes:
        - ./data-models:/usr/local/apache2/htdocs/
    logging: *default-logging

    # healthcheck:
    #   test: (wget --server-response --spider --quiet  http://ld-context/datamodels.context-ngsi.jsonld 2>&1 | awk 'NR==1{print $$2}'|  grep -q -e "200") || exit 1
 
  circuloos-orion:
    labels:
      org.eurodyn: 'circuloos'
      logging: "promtail"
      logging_jobname: "containerlogs"
    platform: linux/amd64
    image: quay.io/fiware/orion-ld:${ORION_LD_VERSION}
    hostname: circuloos-orion
    container_name: circuloos-orion
    restart: always
    depends_on:
      - circuloos-mongo-db
    networks:
      - circuloos
    # expose:
    #   - "${ORION_LD_PORT}:${ORION_LD_PORT}"
    ports:   # for communication outside docker environment BUT only localhost
      - "127.0.0.1:${ORION_LD_PORT}:${ORION_LD_PORT}"
    expose: # for monitoring via prometheus
      - 8000:8000
    environment:
      - ORIONLD_TROE=TRUE
      - ORIONLD_TROE_USER=${ORIONLD_TROE_USER}
      - ORIONLD_TROE_PWD=${ORIONLD_TROE_PWD}
      - ORIONLD_TROE_HOST=circuloos-timescale-db
      - ORIONLD_MONGOCONLY=TRUE
      - ORIONLD_MONGO_HOST=circuloos-mongo-db
      - ORIONLD_MONGO_POOL_SIZE=20
      - ORIONLD_MULTI_SERVICE=TRUE
      - ORIONLD_DISABLE_FILE_LOG=TRUE
      - ORIONLD_FORWARDING=TRUE
    command: -logLevel DEBUG  -troePoolSize 10 -lmtmp
    healthcheck:
      test: curl --fail -s http://circuloos-orion:${ORION_LD_PORT}/version || exit 1
      interval: 10s
    logging: *default-logging

  # Databases
  circuloos-mongo-db:
    labels:
      org.eurodyn: 'circuloos'
      logging: "promtail"
      logging_jobname: "containerlogs"
    image: mongo:${MONGO_DB_VERSION}
    hostname: circuloos-mongo-db
    container_name: circuloos-mongo-db
    expose:
      - "${MONGO_DB_PORT}:${MONGO_DB_PORT}"
    networks:
      - circuloos
    volumes:
      - circuloos-mongo-db-data:/data/db
      - circuloos-mongo-config:/data/configdb
    healthcheck:
      test: |
        host=`hostname --ip-address || echo '127.0.0.1'`; 
        mongo --quiet $host/test --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)' && echo 0 || echo 1    
      interval: 5s
    logging: *default-logging

networks:
  circuloos:
    labels:
      org.eurodyn: 'circuloos'


volumes:
  circuloos-mongo-db-data: 
  circuloos-mongo-config: 