services:

    registrationtoentities:
      build: .
      hostname: registrationtoentities
      container_name: registrationtoentities
      networks:
        - circuloos
      ports:
        - "8888:8888"
      environment:
        - LOG_LEVEL=DEBUG  #  DEBUG INFO ERROR
        - USERNAME=test-circuloos
        - PASSWORD=2UnGRKm7NW8Wxa9Z3N
        - CLIENT_SECRET=yWv2aRCm3KKMGrj9lMXQcEXY4v80tcFk
        # - DEFAULT_CONTEXThttp://circuloos-ld-context/circuloos-context.jsonld
        # - HTTP_SERVICES_BROKER_URL=https://circuloos-platform.eurodyn.com/kong/keycloak-orion/ngsi-ld/v1/entityOperations/upsert 

 # for debuging 
 # See recieved notifications http://localhost:5055/view_data
 
    recieve_notification_server:
      build: ./recieve_notification_server
      hostname: recieve-notification-server
      container_name: recieve-notification-server
      ports:
        - "5055:5055"
      networks:
        - mpms-network
      environment:
        - FLASK_APP=app.py
        - FLASK_RUN_HOST=0.0.0.0

