
version: "3.8"
services:


  # Quantum Leap is persisting Short Term History to Crate-DB
  circuloos-quantumleap:
    labels:
      org.eurodyn: 'circuloos'
    image: orchestracities/quantumleap:${QUANTUMLEAP_VERSION}
    hostname: circuloos-quantumleap
    container_name: circuloos-quantumleap
    depends_on:
      - circuloos-crate-db
      - circuloos-redis-db
    networks:
      - circuloos
    ports:
      - "127.0.0.1:${QUANTUMLEAP_PORT}:${QUANTUMLEAP_PORT}"
    environment:
      - CRATE_HOST=circuloos-crate-db
      - REDIS_HOST=circuloos-redis-db
      - REDIS_PORT=${REDIS_PORT}
      - LOGLEVEL=DEBUG # DEBUG, INFO, WARNING , ERROR
    logging:
      options:
        max-size: 50m    
    restart: always
    healthcheck:
      test: curl --fail -s http://circuloos-quantumleap:${QUANTUMLEAP_PORT}/version || exit 1

  circuloos-crate-db:
    labels:
      org.eurodyn: 'circuloos'
    image: crate:${CRATE_VERSION}
    hostname: circuloos-crate-db
    container_name: circuloos-crate
    ports:
      # Admin UI
      - "127.0.0.1:4200:4200"
      # Transport protocol
      - "127.0.0.1:4300:4300"
    networks:
      - circuloos
    command: crate  -Cpath.repo=/data -Cauth.host_based.enabled=false  -Ccluster.name=democluster -Chttp.cors.enabled=true -Chttp.cors.allow-origin="*" - CRATE_HEAP_SIZE=3g # see https://crate.io/docs/crate/howtos/en/latest/deployment/containers/docker.html#troubleshooting
    # in host pc /etc/sysctl.conf and configure: vm.max_map_count = 262144
    volumes:
      - circuloos-crate-db:/data
    logging:
      options:
        max-size: 50m
    restart: always
    healthcheck:
       test: curl --max-time 25 circuloos-crate-db:4200 || exit 1
       interval: 30s
       timeout: 30s

  circuloos-redis-db:
    labels:
      org.eurodyn: 'circuloos'
    image: redis:${REDIS_VERSION}
    hostname: circuloos-redis-db
    container_name: circuloos-redis
    networks:
      - circuloos
    ports:
      - "127.0.0.1:${REDIS_PORT}:${REDIS_PORT}" # localhost:6379
    volumes:
      - circuloos-redis-db:/data
    logging:
      options:
        max-size: 50m
    restart: always
    healthcheck:
      test: |
        host=`hostname -i || echo '127.0.0.1'`;
        ping=`redis-cli -h "$host" ping` && [ "$ping" = 'PONG' ] && echo 0 || echo 1
      interval: 10s

  recieve_notification_server:
    build: ./recieve_notification_server
    hostname: recieve-notification-server
    container_name: recieve-notification-server
    ports:
      - "5055:5055"
    networks:
      - circuloos
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      
volumes:
  circuloos-crate-db: 
  circuloos-redis-db:
