global:
  resolve_timeout: 5m
  smtp_from: 'noreply@ramp.eu'
  smtp_smarthost: 'parnitha.eurodyn.com:25'

route:
  group_by: ['orion_alerts']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h 
  receiver: 'bf-micocraft-server-notifications'

receivers:
- name: 'bf-micocraft-server-notifications'
  email_configs:
  - to: 'konstantinos.gombakis@eurodyn.com'  # Email where you want to send notifications
    send_resolved: true
    require_tls: false # needed for every additional email !!!
